### ISSUE TITLE
Bug: Doesn’t mute on lock

### ISSUE THREAD

**Issue by GeoffreyBooth** [yonilevy/automute#11]
I have a Mac Pro that I moved into a bedroom. I have a hot corner configured to lock the computer; whenever I get up, I move the mouse cursor into the corner and the Mac locks and the screens turn off. I expected this app to mute my machine when this happens, but the speaker remains unmuted.

I suspect this is because my machine has many audio outputs—the Mac Pro’s builtin speaker, each monitor’s speaker, a Bluetooth headset and an Apple TV in my living room—and the intent of the app is to mute only when the headphones are disconnected. But in my case, the headphones/headset are never disconnected; the headset remains paired with the Mac all the time while it charges on my desk.

Could there be an option to _always_ mute on lock, for whatever the selected audio output is, regardless of whether or not the headphones are connected?

**Comment by yonilevy** [comment]
Thanks for submitting this! You are 100% in the right, the current app behavior is incorrect.

What makes this a bit more complicated, is that there's a bigger issue at the root of this misbehavior: the app currently cares about whether headphones are *connected* where it should care about whether headphones are *the current output device*. (In previous MacOS versions where switching between audio output devices wasn't as streamlined it made more sense, now it's unacceptable).

OTTOMH, to properly fix this, the app should be able to: (1) know whether headphones are *the current output device* and maybe also (2) mute a specific device (not just the current one).

Also (3): the "proper" behavior isn't trivial, for example in your scenario where there are multiple devices connected while the Mac gets locked, which one should be muted? The current one? All of them? The current one + the built-in speakers? Should some of them be "unmuted" after the next login?

I need to give this a bit of thinking / testing...

**Comment by GeoffreyBooth** [comment]
Thanks for investigating this. Can it just mute all devices on lock? Why does it need to do anything special regarding headphones?

I wouldn’t want it to mute the headphones but still play alert chimes from speakers. I also wouldn’t want it to mute the current device at the time of lock, but then my Bluetooth headphones run out of battery and the speakers become the active device and start playing audio. An app called AutoMute I would expect to mute my system, full stop 😄 unless I configure it otherwise.

If it can unmute the current device (or all devices) when it gets unlocked, that would be great, but a nice-to-have in my opinion.

Also, I recently replaced that Mac Pro with a laptop MacBook Pro that I leave on my desk, continuously connected to both speakers and a Bluetooth headset. It has the same issue.

**Comment by yonilevy** [comment]
Thanks again @GeoffreyBooth, this is great feedback!

I could get into why I'd rather not mute headphones on lock, but there's no point as there's no way to 100% distinguish between headphones and speakers, and proper speaker muting is worth the headphone muting side-effect.

_(for reference: it's possible to drastically improve our headphone/speaker classification by looking at BT devices minor device class [requires BT capability when sandboxed + roughly matching the BT device with its AudioObject counterpart through UID string comparisons], but that still leaves wired speakers with no solution)._

So yeah, I think it'd be best to just mute stuff on lock/sleep as you suggest.

I'll probably play with over the weekend and commit the changes, will update.

**Comment by GeoffreyBooth** [comment]
Thanks, that sounds great.

As for providing a way to mute everything except headphones, to me that sounds like you need to provide some way to allow for configuration. Mute everything on lock by default, and a settings dialog can allow for variations like “on lock, mute everything except the AirPods sound output” or “on lock, mute only the External Speakers sound output,” based on the list of sound output devices that you read from the OS. Then you don’t need to tell apart headphones from other types of outputs; the user is telling you which ones the headphones are, to create an exception for them. (Or maybe the user wants to create an exception for the speakers, or for the speakers built into the monitors, or whatever; better to let the user decide than have something specific to headphones.)

**Comment by yonilevy** [comment]
Yes, I thought about that, but I'd rather have as few settings as possible. A good solution tho if/when people complain about this behavior.
