### ISSUE TITLE
Automute not working with headphones connected to USB dock

### ISSUE THREAD

**Issue by nerolite** [yonilevy/automute#4]
**Issue**
Disconnecting my dock does not mute any audio. I have my headphones connected through minijack to a USB dock which is again connected to my Macbook Pro through the USB 3 type-A interface.

**Solution**
* Ensure all audio interfaces are muted.

**Comment by nnathan** [comment]
I think the solution makes sense.

does the dock implement a second audio interface?

**Comment by nerolite** [comment]
![2019-09-24_11-13-32](https://user-images.githubusercontent.com/6739079/65498567-6cace980-debc-11e9-8ed3-51eb8437e128.png)

The dock shows up as its own sound output (Lenovo USB Audio).

**Comment by nerolite** [comment]
Just checking if I provided the necessary details, or if I should supplement the information?
@nnathan

**Comment by yonilevy** [comment]
That's interesting. Currently my goal is to mute/unmute the sound on headphones disconnect/connect, I don't think I'd like to unmute when other devices connect, but perhaps muting on disconnect makes sense. It'd be interesting if you could run the app in Debug mode (through Xcode) and check the logs for the `Stream Terminal Type` when you connect/disconnect your device (emitted [here](https://github.com/yonilevy/automute/blob/master/automute/MJHeadphoneDetector.cpp#L132)), perhaps we could learn more about our options from that.

**Comment by yonilevy** [comment]
Closing, if this is still relevant please provide more information from the log.
