### ISSUE TITLE
Allow undocking status bar item

### ISSUE THREAD

**Issue by nerolite** [yonilevy/automute#5]
**Feature request**: It is preferable to be able to hide the status menu icon. Once having done the initial setup there is little to no reason for having it in the menu bar. Please allow the icon to be hidden (and shown again by relaunching the app).

**Comment by yonilevy** [comment]
I like that! To copy paste from another issue: I'll try to see if i find some time to implement that, otherwise a contribution would be welcomed.

**Comment by yonilevy** [comment]
added here: 5eec23e
