### ISSUE TITLE
Feature Suggestion: Mute on Lockscreen

### ISSUE THREAD

**Issue by fire1ce** [yonilevy/automute#6]
Is it posable to add Mute on Lockscreen?

**Comment by yonilevy** [comment]
That's a great idea! Should be easily done using [this](https://stackoverflow.com/a/1561512), I'll try to see if i find some time to implement that, otherwise a contribution would be welcomed.

**Comment by nnathan** [comment]
I don't mind taking a stab at this. Good information @yonilevy.

I assume we just want to mute on lockscreen but manually unmute as in every other use case?

**Comment by fire1ce** [comment]
buy your names, you both from israel. Cheers for contributing for our nation. 🤗

**Comment by yonilevy** [comment]
Thanks @nnathan but no, I believe it should only mute upon entering lockscreen and display a notification when unlocking, exactly like what the app does today with `willSleep`/`didWake` [here](https://github.com/yonilevy/automute/blob/master/automute/AppDelegate.mm#L46) (in fact I believe just listening on the lock screen notifications and calling the same methods should do the job)

**Comment by nnathan** [comment]
Cool cool. I'll try give it a shot tonight. First venture _hacking_ ObjC.

**Comment by hello-jason** [comment]
@nnathan were you ever able to explore this feature idea?

**Comment by yonilevy** [comment]
@hello-jason Thanks for the reminder! Added!
