### ISSUE TITLE
[CHANGE REQUEST] Update Menubar Icon to match BigSur Icon Style

### ISSUE THREAD

**Issue by qoomon** [yonilevy/automute#7]
Thanks a lot for this handy little util.

Would be nice to see an updated transparent menu bar icon matching the BigSur icon styles.

**Comment by qoomon** [comment]
Big Sur was released. Any news on icon update?

**Comment by Uhtredtb** [comment]
also need this icon update too ➕

**Comment by yonilevy** [comment]
Updated icon in e123d1c, tried to imitate Big Sur's volume icon style.
